apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
  namespace: hka-vsmlab
  labels:
    app: vsmlab
    tier: database
    type: storage
spec:
  storageClassName: hostpath
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Secret
metadata:
  name: mysql
  namespace: hka-vsmlab
  labels:
    app: vsmlab
    tier: database
    type: secret
stringData:
  database: default
  rootpw: eurPMsOohfSDKKss8dD=sW5WLod9
  productspw: FLLzmWv0QHhepVFh37HC0cTQ7kpmsIIE
  categoriespw: cG3zpoZLasOkpbAg67HzrvIOSAT3rCVC
  usermanagementpw: Q1eU2RGSv31iY0GCnPN5kdIWo82Cbns62Wt8PJL+
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: hka-vsmlab
  labels:
    app: vsmlab
    tier: database
    type: service
spec:
  ports:
    - port: 3306
      protocol: TCP
      name: tcp-mysql
  selector:
    app: vsmlab
    tier: database
    type: statefulset
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
  namespace: hka-vsmlab
  labels:
    app: vsmlab
    tier: database
    type: statefulset
spec:
  serviceName: mysql
  selector:
    matchLabels:
      app: vsmlab
      tier: database
      type: statefulset
  template:
    metadata:
      labels:
        app: vsmlab
        tier: database
        type: statefulset
        version: "5.7.9"
      annotations:
        sidecar.istio.io/inject: "true"
    spec:
      restartPolicy: Always
      containers:
        - image: docker.io/bitwrk/web-shop-database:latest
          name: mysql
          env:
            - name: MYSQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: mysql
                  key: database
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql
                  key: rootpw
            - name: MYSQL_PRODUCTS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql
                  key: productspw
            - name: MYSQL_CATEGORIES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql
                  key: categoriespw
            - name: MYSQL_USERMANAGEMENT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql
                  key: usermanagementpw
          ports:
            - containerPort: 3306
              name: mysql
          volumeMounts:
            - name: mysql-volume
              mountPath: /var/lib/mysql
              subPath: data
      volumes:
        - name: mysql-volume
          persistentVolumeClaim:
            claimName: mysql-pvc
